
DROP TABLE IF EXISTS price;
DROP TABLE IF EXISTS brand;
DROP TABLE IF EXISTS product;


CREATE TABLE brand (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  creation_date TIMESTAMP NOT NULL,
  modification_date TIMESTAMP DEFAULT NULL
);

CREATE TABLE product (
  id INT AUTO_INCREMENT(35455,1)  PRIMARY KEY,
  description VARCHAR(250) NOT NULL,
  creation_date TIMESTAMP NOT NULL,
  modification_date TIMESTAMP DEFAULT NULL
);

CREATE TABLE price (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  start_date TIMESTAMP NOT NULL,
  end_date TIMESTAMP,
  priority int NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  currency VARCHAR(4) NOT NULL DEFAULT 'EUR',
  product_id INT NOT  NULL,
  brand_id INT NOT NULL,
  creation_date TIMESTAMP NOT NULL,
  modification_date TIMESTAMP DEFAULT NULL
);
